// @ts-check
const path = require('node:path');

const eslint = require('@eslint/js');
const { defineConfig } = require('eslint/config');
const boundaries = /** @type {import('eslint').ESLint.Plugin} */ (
  require('eslint-plugin-boundaries')
);
const tailwindcss = /** @type {import('eslint').ESLint.Plugin} */ (
  /** @type {unknown} */ (require('eslint-plugin-tailwindcss'))
);
const tseslint = require('typescript-eslint');
const angular = require('angular-eslint');

module.exports = defineConfig([
  {
    files: ['**/*.ts'],
    extends: [
      eslint.configs.recommended,
      tseslint.configs.recommended,
      tseslint.configs.stylistic,
      angular.configs.tsRecommended,
    ],
    processor: angular.processInlineTemplates,
    plugins: {
      boundaries,
    },
    settings: {
      'boundaries/root-path': __dirname,
      'boundaries/elements': [
        {
          type: 'electron',
          pattern: 'projects/electron',
          partialMatch: false,
        },
        {
          type: 'docs',
          pattern: 'projects/docs',
          partialMatch: false,
        },
      ],
      'import/resolver': {
        typescript: {
          project: './tsconfig.json',
        },
      },
    },
    rules: {
      'boundaries/dependencies': [
        'error',
        {
          default: 'disallow',
          checkAllOrigins: false,
          checkUnknownLocals: false,
          checkInternals: false,
        },
      ],
      '@angular-eslint/directive-selector': [
        'error',
        {
          type: 'attribute',
          prefix: 'app',
          style: 'camelCase',
        },
      ],
      '@angular-eslint/component-selector': [
        'error',
        {
          type: 'element',
          prefix: 'app',
          style: 'kebab-case',
        },
      ],
      '@angular-eslint/sort-keys-in-type-decorator': 'error',
      '@angular-eslint/prefer-output-readonly': 'error',
      '@angular-eslint/prefer-on-push-component-change-detection': 'error',
      '@angular-eslint/prefer-standalone': 'error',
      '@angular-eslint/prefer-signals': 'error',
      '@angular-eslint/prefer-signal-model': 'error',
      '@angular-eslint/component-max-inline-declarations': ['error', { template: 10, styles: 0 }],
      '@angular-eslint/inject-at-top': 'error',
      'no-unused-private-class-members': 'off',
      '@typescript-eslint/no-unused-private-class-members': 'error',
      'max-lines': ['error', { max: 500, skipBlankLines: false, skipComments: false }],
    },
  },
  {
    files: ['**/*.html'],
    extends: [angular.configs.templateRecommended, angular.configs.templateAccessibility],
    rules: {
      '@angular-eslint/template/prefer-self-closing-tags': 'error',
      '@angular-eslint/template/prefer-control-flow': 'error',
      '@angular-eslint/template/prefer-at-else': 'error',
      '@angular-eslint/template/prefer-at-empty': 'error',
      '@angular-eslint/template/button-has-type': 'error',
      '@angular-eslint/template/attributes-order': 'error',
      '@angular-eslint/template/no-any': 'error',
      '@angular-eslint/template/prefer-contextual-for-variables': 'error',
      'max-lines': ['error', { max: 500, skipBlankLines: false, skipComments: false }],
    },
  },
  {
    files: ['**/*.ts', '**/*.html'],
    plugins: {
      tailwindcss,
    },
    settings: {
      tailwindcss: /** @type {import('eslint-plugin-tailwindcss').PluginSettings} */ ({
        cssConfigPath: path.join(__dirname, 'projects/electron/src/styles.css'),
      }),
    },
    rules: {
      'tailwindcss/classnames-order': 'error',
      'tailwindcss/enforces-negative-arbitrary-values': 'error',
      'tailwindcss/enforces-shorthand': 'error',
      'tailwindcss/important-modifier-suffix': 'error',
      'tailwindcss/no-arbitrary-value': 'error',
      'tailwindcss/no-contradicting-classname': 'error',
      'tailwindcss/no-custom-classname': [
        'warn',
        {
          whitelist: [
            'about-header',
            'actions',
            'app-content',
            'brand',
            'bulk-delete-button',
            'candidate-card',
            'candidate-list',
            'choice-label',
            'cleanup-options',
            'close-action',
            'close-icon',
            'column-actions',
            'column-button',
            'column-card',
            'column-count',
            'column-drag-preview',
            'column-fields',
            'column-form',
            'column-list',
            'column-row',
            'column-tab-content',
            'confetti-canvas',
            'content-shell',
            'converted-cleanup-checkbox',
            'dataset-column-tabs',
            'dataset-count',
            'dataset-name-button',
            'dataset-option',
            'dataset-option-content',
            'dataset-option-details',
            'dataset-picker',
            'dataset-type-options',
            'delete-selected-button',
            'description',
            'detail-section',
            'details',
            'dialog-actions',
            'documentation-card',
            'documentation-label',
            'drag-handle',
            'empty-choice',
            'empty-state',
            'empty-step',
            'error',
            'external-actions',
            'eyebrow',
            'facts',
            'facts-card',
            'fallback-message',
            'filter-button',
            'filter-count',
            'filter-fields',
            'filter-form',
            'footer-inner',
            'footer-links',
            'footer-meta',
            'format-options',
            'hero',
            'hero-content',
            'identity',
            'import-dataset',
            'import-table-container',
            'import-tables',
            'import-validation',
            'imported-cleanup-checkbox',
            'issue',
            'issue--error',
            'issue--warning',
            'issue-list',
            'issue-section',
            'legal',
            'live-announcement',
            'loading-state',
            'name-field',
            'nav-group',
            'nav-group-label',
            'navigation-heading',
            'navigation-trigger',
            'no-issues',
            'notice',
            'notice--error',
            'page',
            'page-content',
            'page-header',
            'path-list',
            'qdb-wizard',
            'remove-source',
            'result-step',
            'results',
            'review-card',
            'review-fields',
            'review-list',
            'row-count',
            'row-select-checkbox',
            'sample-note',
            'search-field',
            'section-actions',
            'section-eyebrow',
            'sections',
            'select-all-checkbox',
            'selected-dataset',
            'selected-dataset-heading',
            'selection-footer',
            'site-header',
            'skip-link',
            'source-card',
            'source-card-header',
            'source-fields',
            'source-icon',
            'source-identity',
            'source-kind',
            'source-metadata',
            'source-path',
            'source-picker',
            'source-title',
            'source-warning',
            'source-warnings',
            'step-actions',
            'step-content',
            'step-intro',
            'storage-card',
            'storage-footer',
            'success',
            'summary',
            'table-container',
            'table-controls',
            'table-name-list',
            'table-scroll',
            'table-summary',
            'table-summary-list',
            'table-warnings',
            'target-picker',
            'toolbar-spacer',
            'utility-actions',
            'validation-failed',
            'validation-metadata',
            'validation-pending',
            'validation-progress',
            'validation-summary',
            'version',
            'version-select',
            'visually-hidden',
            'warning-list',
            'wizard-card',
          ],
        },
      ],
      'tailwindcss/no-unnecessary-arbitrary-value': 'error',
    },
  },
]);
